logDebug("START OF COMMUNICATION SEND EMAIL AFTER TEST!");

aa.print("START OF COMMUNICATION SEND EMAIL AFTER TEST!");

aa.print("END OF COMMUNICATION SEND EMAIL AFTER TEST!");

logDebug("END OF COMMUNICATION SEND EMAIL AFTER TEST!");